---
- hosts: localhost
  gather_facts: no
  
  tasks: 
    - name: Run rulebook
      command: ansible-rulebook --rulebook webhook-example.yml -i inventory.yml --verbose
      environment: 
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk 
        
